# Generated by Django 2.0 on 2019-05-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=256)),
                ('rut', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(verbose_name=45)),
                ('correo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_producto', models.IntegerField(verbose_name=45)),
                ('marca_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(verbose_name=45)),
                ('mes', models.IntegerField(verbose_name=45)),
                ('año', models.IntegerField(verbose_name=45)),
                ('Hora', models.IntegerField(verbose_name=45)),
                ('Clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=256)),
                ('precio', models.IntegerField(verbose_name=45)),
                ('espacio_fisico', models.CharField(max_length=256)),
                ('tiempo_de_duracion', models.IntegerField(verbose_name=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_has_Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Inventario')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=256)),
                ('rut', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(verbose_name=45)),
                ('correo', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=256)),
                ('funcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores_has_Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Servicios')),
                ('trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Trabajadores')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='Trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.Trabajadores'),
        ),
    ]
